EVEREST-91 DatabaseBackups API
percona/dbaas-operator pull request #108
Opened 2023-06-22 16:20 UTC by oksana-grishchenko

EVEREST-91 
The idea is to create the DatabaseBackup CR and get the backups general info from the upstream operators. The new resource CRUD will be proxied to the BE once implemented.  

In the future we probably will need to cache the backups information on the BE side for the disaster recovery scenarios when the k8s cluster is not available anymore and there is no way to get info from the upstream operators, but this problem is out of scope currently.

2023-06-28 11:47 UTC, michal-kralik requested changes

2023-06-28 11:47 UTC, michal-kralik commented on api/v1/databaseclusterbackup_types.go
> +// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
Is this file maybe a leftover?

2023-06-28 14:39 UTC, oksana-grishchenko commented on api/v1/databaseclusterbackup_types.go
> +// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Age of the resource"
This is all I've changed manually and what's basically needs to be reviewed. Everything else was generated by 

- `operator-sdk create api --group dbaas --version v1 --kind DatabaseClusterBackup --resource --controller`
- `make generate`
- `make bundle`
- `make deploy/bundle.yaml`

2023-06-28 15:05 UTC, michal-kralik approved these changes

2023-06-29 08:15 UTC, gen1us2k approved these changes

2023-06-29 08:15 UTC, merged